### PR TITLE
Can you provide an example of desktop sharing?

### PR DESCRIPTION
**Pull request by liujiaxiang**
I can't find an example of desktop sharing, Can you provide an example? 

thank you!

### CODE REVIEW

**Comment by j1elo** [comment]
Will ask the team to show a desktop sharing tutorial or demo. Closing this PR as it has accumulated all commits since creation date.

**Comment by pavlobu** [comment]
Hello, any update on this? Thanks!

**Comment by micaelgallego** [comment]
Take a look to [OpenVidu](https://openvidu.io). Is a platform based on Kurento (developed by the same team) that provides desktop sharing out of the box.

**Comment by pavlobu** [comment]
thanks a lot!

**Pull request closed without merging**
