### PR TITLE
Changed resgister typo to register

### PR DESCRIPTION
**Pull request by lotas**
Hi guys :)

I know that this is not a real problem, but I decided to do this Pull Request anyway, striving for some consistency and language purity :D

Didn't find any discussions justifying usage of *resgister* instead of *register*, so here it goes.

Thanks!

### CODE REVIEW

**Comment by sshilko** [comment]
dont do it, its a trap

**Comment by igracia** [comment]
Yap, it's a typo. Thanks for pointing that out!

**Comment by igracia** [comment]
[There](https://github.com/Kurento/kurento-tutorial-java/commit/bfa36f575155323dc6082d5df0ba2855c74869d2) you go

**Comment by lotas** [comment]
Cool! Thanks!

**Comment by sqq222** [comment]
Pray for a complete example of kurento on Android phones.

**Pull request closed without merging**
